---

- hosts: all
  become: true
  tasks:

  - name: Update CentOS repos
    dnf:
      update_cache: yes
    when: ansible_distribution == "Centos"

  - name: Update AWS Linux repos
    yum:
      update_cache: yes
    when: ansible_distribution == "Amazon"
  
  - name: Install apache2 package on CentOS
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Centos"

  - name: Install apache2 package on AWS Linux
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "Amazon"

  - name: boot up apache server
    ansible.builtin.systemd:
      state: started
      name: httpd
  
  - name: permit http traffic
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled
