---

- hosts: all
  become: true
  tasks:
  
  - name: Install apache & php package on AWS Linux
    package:
      name:
        - "{{ httpd_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: boot up apache server
    ansible.builtin.systemd:
      state: started
      name: httpd
