---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Install updates (Amazon)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: Install unzip
    tags: workstation,unzip,zip
    package:
      name: unzip

  - name: Install terraform
    tags: workstation,terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
      
- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache and PHP (Amazon)
    tags: apache,apache2,amazon
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: Spin Up Apache Website (Amazon)
    tags: apache,apache2,amazon
    ansible.builtin.systemd:
      state: started
      name: httpd
      enabled: yes
    when: ansible_distribution == "Amazon"

  - name: Install Apache and PHP (Ubuntu)
    tags: apache,httpd,centos
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Copy default HTML file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB package (Ubuntu)
    tags: ubuntu,db,mariadb
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install MariaDB package (Amazon)
    tags: amazon,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon"

- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba Package
    tags: samba
    package:
      name: samba
      state: latest
