- name: Install Apache and PHP (Amazon)
  tags: apache,apache2,amazon
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "Amazon"

- name: Spin Up Apache Website (Amazon)
  tags: apache,apache2,amazon
  ansible.builtin.systemd:
    state: started
    name: httpd
    enabled: yes
  when: ansible_distribution == "Amazon"

- name: Install Apache and PHP (Ubuntu)
  tags: apache,httpd,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Change e-mail address for Admin (Amazon)
  tags: apache,httpd,amazon
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Amazon"
  register: httpd

- name: Restart httpd (Amazon)
  tags: apache,httpd,amazon
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: Copy default HTML file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
