- name: Install Apache and PHP (Amazon)
  tags: apache,apache2,amazon
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Amazon"

- name: Spin Up Apache Website (Amazon)
  tags: apache,apache2,amazon
  ansible.builtin.systemd:
    state: started
    name: "{{ apache_service }}"
    enabled: yes

- name: Change e-mail address for Admin (Amazon)
  tags: apache,httpd,amazon
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution == "Amazon"
  notify: restart_apache 

- name: Copy default HTML file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
